### ISSUE TITLE
Reference d'appel

### ISSUE THREAD

**Issue by smoysan** [soapower/soapower#19]
Je souhaiterais pourvoir identifier les appels enregistrés en BDD par l'intermédiaire d'une référence passée dans un attribut de l'appel. Cette référence pourrait être affichée dans la page de live ou search.

Serait-il possible de configurer (en xpath par exemple) l'attribut que l'on souhaité voir apparaitre en référence par service?

**Comment by yesnault** [comment]
Un attribut dans le header HTTP ou dans le corps de la requête ?

**Comment by smoysan** [comment]
Dans le corps de la requête, typiquement une référence de message.

**Comment by yesnault** [comment]
Finalement, cela revient à faire une recherche dans la requête ou la réponse d'un webservice. La mise en place n'est pas si simple que cela, actuellement, pour des problématiques de quantité et de taille de réponses, les requetes / reponses sont gzippées en base (mysql). Il est donc impossible à postériori de faire la recherche.

Deux solutions : 
- Soit on rajoute un traitement qui permet de faire des actions (extraire le contenu de la requête xpath par exemple) lors de l'arrivée de la requête ou de la réponse
- Soit on change de backend en mettant une base noSql qui semble bien plus adaptée pour faire des recherches à postériori sur des trames échangées.

Je suis plutôt partant sur la seconde solution, un peu plus radicale, mais qui a pour avantage de pouvoir faire des recherches à postériori sur n'importe quelle donnée des trames. Il restera à voir comment on affiche cela sur le live (qui ne se base pas sur la db pour afficher ces informations)

Je ferme cette demande, elle sera traitée ici : #21
