### ISSUE TITLE
Search in Request / Response.

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#21]
New Backend -> NoSql (Mongodb)

**Comment by fsamin** [comment]
This is the major enhancement of 2.0.
Please also add a such mechanism to the filter on the "live" page.

**Comment by yesnault** [comment]
RequestData are now stored in mongoDB (no msyql anymore). The field response of collections requestData store response in clear. The field responseOriginal contains response in bytes if there is a hearder gzip.

**Comment by yesnault** [comment]
Done by @guilefranc thanks !
