### ISSUE TITLE
Keep monitoring stats

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#3]

**Comment by smoysan** [comment]
Bonjour,

Serait-il effectivement possible de conserver indéfiniment les données (appels, stats etc..)?

**Comment by yesnault** [comment]
Il n'y a pas de purge sur les stats.
La purge des appels (données XML ou tout) est déjà paramétrable. Tu peux très bien mettre 365j ou 3650j (autant dire infini...)...

Cette issue doit permettre de calculer des vraies moyennes sur plusieurs jours. Actuellement, il y a une moyenne 90 percentiles par jour, mais si l'on demande une moyenne sur 5j, la moyenne est calculée sans pondération.

**Comment by yesnault** [comment]
Done on v2.0 (in statistics collection)
