### ISSUE TITLE
Analysis ne fonctionne plus depuis la version 1.0.3

### ISSUE THREAD

**Issue by fsamin** [soapower/soapower#32]
Aucune donnée ne remonte sur l'onglet "Analysis" alors qu'elles sont bien présentes dans l'onglet "search" sur le même environnement.
Merci

**Comment by yesnault** [comment]
La page analysis ne montre que les stats 90percentiles à J+1. Tu regardais bien les stats de la veille au minimum ?

**Comment by fsamin** [comment]
Oui, je confirme.

**Comment by yesnault** [comment]
Finalement, je pense que le calcul de stats n'a jamais bien marché :)
