### ISSUE TITLE
Show Soapower release number in the footer and docs

### ISSUE THREAD

**Issue by fsamin** [soapower/soapower#69]
Hi guys,
Please add the soapower release number in the footer. 
Modify the link to documentation to link directly to the right version of the docs.
Thks

**Comment by yesnault** [comment]
It's done on 2.0.x (using https://github.com/sbt/sbt-buildinfo). Push today.

**Comment by fsamin** [comment]
Great !
Please add it on 1.4.0 :-)

**Comment by yesnault** [comment]
It's backported on 1.4.x
