### ISSUE TITLE
Syntax highlighting and pretty print

### ISSUE THREAD

**Issue by fsamin** [soapower/soapower#70]
When showing request content either XML or JSON add syntax highlighting and pretty print.

**Comment by yesnault** [comment]
Possible for version 2 ? the merges become increasingly complicated from 1.4.x to 2.0.x

**Comment by fsamin** [comment]
yep, I just changed the milestone

**Comment by guilefranc** [comment]
Done with 7a150439f4fe70ba72dc36d0ef57f370e92e62bb
