### ISSUE TITLE
[Rest] Wrong service selected

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#72]
I have two services, httpMethod GET : 

/rest/yesnault/table     http://localhost:9010/services/all/listDatatable
/rest/yesnault/table2    http://localhost:9010/environments/all/options

When I get /rest/yesnault/table2, http://localhost:9010/services/all/listDatatable is called

Why https://github.com/soapower/soapower/blob/1.4.x/app/controllers/Rest.scala#L267 check with startWith ?
And why this is not done with sql instead of select all services of environment / http Method here : https://github.com/soapower/soapower/blob/1.4.x/app/controllers/Rest.scala#L147

**Comment by yesnault** [comment]
And i think there is a side effect. When i get /rest/yesnault/table2, it's a call on  http://localhost:9010/services/all/listDatatable2 !

**Comment by guilefranc** [comment]
It's a misunderstanding of the service notion in soapower. on my part

I'll fix that to use SQL directly

**Comment by guilefranc** [comment]
It should work now

**Comment by yesnault** [comment]
Ok, it's fixed with https://github.com/soapower/soapower/commit/2bc62b8a6222e66dc97d36aae5237f0cdf9f55ec
