### ISSUE TITLE
[REST] Large response truncated

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#73]
I have a localTarget : 
http://localhost:9000/rest/yesnault/table
with the remote target : 
http://localhost:9010/services/all/listDatatable    

The remote give a large response (this is a Soapower alive, with 3302 services...)

When i ask remote target, the response begin with : 

```
{"iTotalRecords":3302,"iTotalDisplayRecords":3302,"data":[{"id":"3295" ...
```

When i ask local target, i have : 

```
e14fa
{"iTotalRecords":3302,"iTotalDisplayRecords":3302,"data":[{"id":"3295" ...
```

What is e14fa ?
And the data is truncated...

**Comment by guilefranc** [comment]
e14fa correspond to the hexadecimal length of the chunked data sent. Normally, It shouldn't be interpret.

**Comment by guilefranc** [comment]
It seems that there is a problem when using the chunk method on large data https://github.com/soapower/soapower/blob/1.4.x/app/controllers/Rest.scala#L246

If we use the apply method instead, the data is properly sent to the client.

**Comment by yesnault** [comment]
Ok, it's fixed with https://github.com/soapower/soapower/commit/550c4a8d94a3860042a991460dc4973e6d09c4a4

**Comment by yesnault** [comment]
Arf, bug open in 2.0.0...
