### ISSUE TITLE
Real Time 90 percentiles stats

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#81]
Hi,

We have 90percentiles stats for data at day + 1. Is it possible to have a checkbox (on stats / analysis page) to compute stats on collection RequestData (compute with MongoDB aggregation Framework) ?

Thks

**Comment by guilefranc** [comment]
Hi,

Yes, I start working on it.

**Comment by yesnault** [comment]
Done with https://github.com/soapower/soapower/commit/3c4c496c852adfeb0480ba2dff605cf80de013df and https://github.com/soapower/soapower/commit/93de6ca0e113f4e5ca493f2a0b1e89d229d9b955 Thks !
